"""Ajout des champs pour empreintes digitales

Revision ID: d65d284de9fd
Revises: ab54ddead279
Create Date: 2025-05-13 15:06:42.291918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65d284de9fd'
down_revision: Union[str, None] = 'ab54ddead279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('fingerprint_right_path', sa.String(length=255), nullable=True))
    op.add_column('person', sa.Column('fingerprint_left_path', sa.String(length=255), nullable=True))
    op.add_column('person', sa.Column('fingerprint_thumbs_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'fingerprint_thumbs_path')
    op.drop_column('person', 'fingerprint_left_path')
    op.drop_column('person', 'fingerprint_right_path')
    # ### end Alembic commands ###
