"""Add binary image data to Person model

Revision ID: e36da302aeb4
Revises: 6a735b3a026e
Create Date: 2025-05-17 11:20:05.044728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36da302aeb4'
down_revision: Union[str, None] = '6a735b3a026e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo_data', sa.LargeBinary(), nullable=True))
    op.add_column('person', sa.Column('photo_mime_type', sa.String(length=30), nullable=True))
    op.add_column('person', sa.Column('fingerprint_right_data', sa.LargeBinary(), nullable=True))
    op.add_column('person', sa.Column('fingerprint_right_mime_type', sa.String(length=30), nullable=True))
    op.add_column('person', sa.Column('fingerprint_left_data', sa.LargeBinary(), nullable=True))
    op.add_column('person', sa.Column('fingerprint_left_mime_type', sa.String(length=30), nullable=True))
    op.add_column('person', sa.Column('fingerprint_thumbs_data', sa.LargeBinary(), nullable=True))
    op.add_column('person', sa.Column('fingerprint_thumbs_mime_type', sa.String(length=30), nullable=True))
    op.alter_column('person', 'photo_path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'photo_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('person', 'fingerprint_thumbs_mime_type')
    op.drop_column('person', 'fingerprint_thumbs_data')
    op.drop_column('person', 'fingerprint_left_mime_type')
    op.drop_column('person', 'fingerprint_left_data')
    op.drop_column('person', 'fingerprint_right_mime_type')
    op.drop_column('person', 'fingerprint_right_data')
    op.drop_column('person', 'photo_mime_type')
    op.drop_column('person', 'photo_data')
    # ### end Alembic commands ###
