"""Add created_by_user field (nullable)

Revision ID: e48b90f77785
Revises: e5d0b9c46344
Create Date: 2025-06-14 19:50:36.615817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48b90f77785'
down_revision: Union[str, None] = 'e5d0b9c46344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('created_by_user', sa.String(length=255), nullable=True))
    op.drop_index('idx_person_age', table_name='person')
    op.drop_index('idx_person_age_gender', table_name='person')
    op.drop_index('idx_person_created_at', table_name='person')
    op.drop_index('idx_person_created_date', table_name='person')
    op.drop_index('idx_person_created_gender', table_name='person')
    op.drop_index('idx_person_created_month', table_name='person')
    op.drop_index('idx_person_created_nationality', table_name='person')
    op.drop_index('idx_person_created_region', table_name='person')
    op.drop_index('idx_person_created_week', table_name='person')
    op.drop_index('idx_person_fingerprints_composite', table_name='person')
    op.drop_index('idx_person_gender', table_name='person')
    op.drop_index('idx_person_gender_nationality', table_name='person')
    op.drop_index('idx_person_has_left_fingerprint', table_name='person')
    op.drop_index('idx_person_has_right_fingerprint', table_name='person')
    op.drop_index('idx_person_has_thumbs_fingerprint', table_name='person')
    op.drop_index('idx_person_name_lower', table_name='person')
    op.drop_index('idx_person_nationality', table_name='person')
    op.drop_index('idx_person_nationality_region', table_name='person')
    op.drop_index('idx_person_recent_first', table_name='person')
    op.drop_index('idx_person_region', table_name='person')
    op.drop_index('idx_person_region_ali_sabieh', table_name='person', postgresql_where="((region)::text = 'Ali-Sabieh'::text)")
    op.drop_index('idx_person_region_arta', table_name='person', postgresql_where="((region)::text = 'Arta'::text)")
    op.drop_index('idx_person_region_dikhil', table_name='person', postgresql_where="((region)::text = 'Dikhil'::text)")
    op.drop_index('idx_person_region_djibouti', table_name='person', postgresql_where="((region)::text = 'Djibouti'::text)")
    op.drop_index('idx_person_region_gender', table_name='person')
    op.drop_index('idx_person_region_lower', table_name='person')
    op.drop_index('idx_person_region_nationality', table_name='person')
    op.drop_index('idx_person_region_obock', table_name='person', postgresql_where="((region)::text = 'Obock'::text)")
    op.drop_index('idx_person_region_tadjourah', table_name='person', postgresql_where="((region)::text = 'Tadjourah'::text)")
    op.drop_index('idx_person_updated_at', table_name='person')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_person_updated_at', 'person', ['updated_at'], unique=False)
    op.create_index('idx_person_region_tadjourah', 'person', ['created_at', 'gender', 'nationality'], unique=False, postgresql_where="((region)::text = 'Tadjourah'::text)")
    op.create_index('idx_person_region_obock', 'person', ['created_at', 'gender', 'nationality'], unique=False, postgresql_where="((region)::text = 'Obock'::text)")
    op.create_index('idx_person_region_nationality', 'person', ['region', 'nationality'], unique=False)
    op.create_index('idx_person_region_lower', 'person', [sa.literal_column('lower(region::text)')], unique=False)
    op.create_index('idx_person_region_gender', 'person', ['region', 'gender'], unique=False)
    op.create_index('idx_person_region_djibouti', 'person', ['created_at', 'gender', 'nationality'], unique=False, postgresql_where="((region)::text = 'Djibouti'::text)")
    op.create_index('idx_person_region_dikhil', 'person', ['created_at', 'gender', 'nationality'], unique=False, postgresql_where="((region)::text = 'Dikhil'::text)")
    op.create_index('idx_person_region_arta', 'person', ['created_at', 'gender', 'nationality'], unique=False, postgresql_where="((region)::text = 'Arta'::text)")
    op.create_index('idx_person_region_ali_sabieh', 'person', ['created_at', 'gender', 'nationality'], unique=False, postgresql_where="((region)::text = 'Ali-Sabieh'::text)")
    op.create_index('idx_person_region', 'person', ['region'], unique=False)
    op.create_index('idx_person_recent_first', 'person', [sa.literal_column('created_at DESC'), 'id'], unique=False)
    op.create_index('idx_person_nationality_region', 'person', ['nationality', 'region'], unique=False)
    op.create_index('idx_person_nationality', 'person', ['nationality'], unique=False)
    op.create_index('idx_person_name_lower', 'person', [sa.literal_column('lower(name::text)')], unique=False)
    op.create_index('idx_person_has_thumbs_fingerprint', 'person', [sa.literal_column('(fingerprint_thumbs_data IS NOT NULL)')], unique=False)
    op.create_index('idx_person_has_right_fingerprint', 'person', [sa.literal_column('(fingerprint_right_data IS NOT NULL)')], unique=False)
    op.create_index('idx_person_has_left_fingerprint', 'person', [sa.literal_column('(fingerprint_left_data IS NOT NULL)')], unique=False)
    op.create_index('idx_person_gender_nationality', 'person', ['gender', 'nationality'], unique=False)
    op.create_index('idx_person_gender', 'person', ['gender'], unique=False)
    op.create_index('idx_person_fingerprints_composite', 'person', [sa.literal_column('(fingerprint_right_data IS NOT NULL OR fingerprint_left_data IS NOT NULL OR fingerprint_thumbs_data IS NOT NULL)'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_person_created_week', 'person', [sa.literal_column('EXTRACT(year FROM created_at)'), sa.literal_column('EXTRACT(week FROM created_at)')], unique=False)
    op.create_index('idx_person_created_region', 'person', ['created_at', 'region'], unique=False)
    op.create_index('idx_person_created_nationality', 'person', ['created_at', 'nationality'], unique=False)
    op.create_index('idx_person_created_month', 'person', [sa.literal_column('EXTRACT(year FROM created_at)'), sa.literal_column('EXTRACT(month FROM created_at)')], unique=False)
    op.create_index('idx_person_created_gender', 'person', ['created_at', 'gender'], unique=False)
    op.create_index('idx_person_created_date', 'person', [sa.literal_column('date(created_at)')], unique=False)
    op.create_index('idx_person_created_at', 'person', ['created_at'], unique=False)
    op.create_index('idx_person_age_gender', 'person', ['age', 'gender'], unique=False)
    op.create_index('idx_person_age', 'person', ['age'], unique=False)
    op.drop_column('person', 'created_by_user')
    # ### end Alembic commands ###
